In [6]:
import LinearAlgebra as la

In [38]:
n = 200

C = zeros(2n, 2n)
B1 = rand(n, n)
B2 = rand(n, n)

C[1:n, 1:n] .= B1
C[n+1:end, n+1:end] = B2

@time la.det(C)
@time la.det(B1) * la.det(B2)

  0.005590 seconds (4 allocations: 1.224 MiB)
  0.004929 seconds (9 allocations: 628.672 KiB)


4.768775679762195e160

In [20]:
v = [20,17,13,15,14]
p = sortperm(v)
p2 = sortperm(p)

5-element Vector{Int64}:
 5
 4
 1
 3
 2

In [26]:
v[p][p2]

5-element Vector{Int64}:
 20
 17
 13
 15
 14

5-element Vector{Int64}:
 5
 4
 1
 3
 2