In [7]:
using Polynomials, SpecialPolynomials

In [13]:
using BenchmarkTools

In [8]:
x = variable(Polynomial{Rational{Int}})

Polynomial(x)

In [20]:
function H10(x)
    30240.0∙x - 80640.0∙x3 + 48384.0∙x5 - 9216.0∙x7 + 512.0∙x9
end

H10 (generic function with 2 methods)

3.27552976e9

11-element Vector{Polynomial{Float64, :x}}:
 Polynomial(1.0)
 Polynomial(2.0*x)
 Polynomial(-2.0 + 4.0*x^2)
 Polynomial(-12.0*x + 8.0*x^3)
 Polynomial(12.0 - 48.0*x^2 + 16.0*x^4)
 Polynomial(120.0*x - 160.0*x^3 + 32.0*x^5)
 Polynomial(-120.0 + 720.0*x^2 - 480.0*x^4 + 64.0*x^6)
 Polynomial(-1680.0*x + 3360.0*x^3 - 1344.0*x^5 + 128.0*x^7)
 Polynomial(1680.0 - 13440.0*x^2 + 13440.0*x^4 - 3584.0*x^6 + 256.0*x^8)
 Polynomial(30240.0*x - 80640.0*x^3 + 48384.0*x^5 - 9216.0*x^7 + 512.0*x^9)
 Polynomial(-30240.0 + 302400.0*x^2 - 403200.0*x^4 + 161280.0*x^6 - 23040.0*x^8 + 1024.0*x^10)

In [98]:
using Polynomials, SpecialPolynomials
x = variable(Polynomial{Rational{Int}})
l = 10
for i in 0:10-1
    print("function H$i(x)\n    $(basis(Hermite, i)(x))\nend\n")
end

function H0(x)
    1.0
end
function H1(x)
    2.0*x
end
function H2(x)
    -2.0 + 4.0*x^2
end
function H3(x)
    -12.0*x + 8.0*x^3
end
function H4(x)
    12.0 - 48.0*x^2 + 16.0*x^4
end
function H5(x)
    120.0*x - 160.0*x^3 + 32.0*x^5
end
function H6(x)
    -120.0 + 720.0*x^2 - 480.0*x^4 + 64.0*x^6
end
function H7(x)
    -1680.0*x + 3360.0*x^3 - 1344.0*x^5 + 128.0*x^7
end
function H8(x)
    1680.0 - 13440.0*x^2 + 13440.0*x^4 - 3584.0*x^6 + 256.0*x^8
end
function H9(x)
    30240.0*x - 80640.0*x^3 + 48384.0*x^5 - 9216.0*x^7 + 512.0*x^9
end


In [33]:
function H0(x)
    1.0
end
function H1(x)
    2.0*x
end
function H2(x)
    -2.0 + 4.0*x^2
end
function H3(x)
    -12.0*x + 8.0*x^3
end
function H4(x)
    12.0 - 48.0*x^2 + 16.0*x^4
end
function H5(x)
    120.0*x - 160.0*x^3 + 32.0*x^5
end
function H6(x)
    -120.0 + 720.0*x^2 - 480.0*x^4 + 64.0*x^6
end
function H7(x)
    -1680.0*x + 3360.0*x^3 - 1344.0*x^5 + 128.0*x^7
end
function H8(x)
    1680.0 - 13440.0*x^2 + 13440.0*x^4 - 3584.0*x^6 + 256.0*x^8
end
function H9(x)
    30240.0*x - 80640.0*x^3 + 48384.0*x^5 - 9216.0*x^7 + 512.0*x^9
end
function H10(x)
    -30240.0 + 302400.0*x^2 - 403200.0*x^4 + 161280.0*x^6 - 23040.0*x^8 + 1024.0*x^10
end

function hermite(x, i)
    if i==0
        return H0(x)
    end
    if i==1
        return H1(x)
    end
    if i==2
        return H2(x)
    end
    if i==3
        return H3(x)
    end
    if i==4
        return H4(x)
    end
    if i==5
        return H5(x)
    end
    if i==6
        return H6(x)
    end
    if i==7
        return H7(x)
    end
    if i==8
        return H8(x)
    end
    if i==9
        return H9(x)
    end
    if i==10
        return H10(x)
    end
end

hermite (generic function with 1 method)

In [69]:
hers = zeros(10)
function eval_hers(x, hers)
    for i in 0:9
        hers[i+1] = hermite(x, i)
    end
    return hers
end

eval_hers (generic function with 1 method)

In [82]:
x = 3.0

3.0

In [84]:
@btime eval_hers(x, hers)

  102.674 ns (0 allocations: 0 bytes)


10-element Vector{Float64}:
       1.0
       6.0
      34.0
     180.0
     876.0
    3816.0
   14136.0
   39024.0
   36240.0
 -406944.0

In [40]:
using Pkg; Pkg.activate("C:\\Users\\KarlH\\Desktop\\ComputationalPhysicsMaster\\Code\\OrbitalNeuralMethods")
using OrbitalNeuralMethods
import OrbitalNeuralMethods as onm

  Activating project at `C:\Users\KarlH\Desktop\ComputationalPhysicsMaster\Code\OrbitalNeuralMethods`


In [71]:
ho = HOBasis(10, 0.25);

In [72]:
hos = zeros(10)
@btime onm.evaluate!(hos, 5, ho);
@btime onm.fast_ho_all!(5, ho::HOBasis);

  75.926 ns (0 allocations: 0 bytes)
  83.264 ns (0 allocations: 0 bytes)


In [80]:
function evaluate_Hermite!(hermites, x)
    hermites[1] = 1.0
    hermites[2] = 2x
    @inbounds for n in 3:length(hermites)
        hermites[n] = 2x * hermites[n-1] - 2(n - 2) * hermites[n-2]
    end
    return hermites
end

evaluate_Hermite! (generic function with 1 method)

In [95]:
hos = zeros(80);

In [94]:
basis(Hermite, 79)(x)

1.4492142713261372e71

In [96]:
evaluate_Hermite!(hos, x);
hos[end]

1.4492142713261408e71

In [86]:
@btime evaluate_Hermite!(hos, x)

  26.078 ns (0 allocations: 0 bytes)


10-element Vector{Float64}:
       1.0
       6.0
      34.0
     180.0
     876.0
    3816.0
   14136.0
   39024.0
   36240.0
 -406944.0